require: 
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'test/**/*'
  TargetRubyVersion: 2.7.0

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ClassStructure:
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - instance_methods
      - protected_methods
      - private_methods

Layout/HeredocIndentation:
  EnforcedStyle: powerpack

# Cannot be less than length of textbook_review_params
Layout/LineLength:
  Max: 650
  
# Trailing white space is meaningful in code examples
Layout/TrailingWhitespace:
  AllowInHeredoc: true

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Metrics/AbcSize:
  Max: 120

Metrics/BlockLength:
  Max: 50
  Exclude: 
    - 'config/routes.rb'

Metrics/BlockNesting:
  Max: 3

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/MethodLength:
  Max: 250

Metrics/PerceivedComplexity:
  Max: 17

Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search

Performance/UnfreezeString:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Style/ClassAndModuleChildren:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/MixinUsage:
  Exclude:
  - 'bin/*'