AWS_ACCESS_KEY_ID: "AKIAJURZY4Z4A27OKACQ"
AWS_SECRET_ACCESS_KEY: "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"
TWITTER_CONSUMER_KEY: "dFPIQW8rTerq2ncKA90NJt8ty"
TWITTER_CONSUMER_SECRET: "Pxg5whATp65Wydc474JtyJ6IDpsw0KgGlR5BNmbT4sbd2RTiVg"