default: &postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

default: &mysql
  adapter: mysql2
  socket: /tmp/mysql.sock
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: root
  password:

development:
  <<: *mysql
  database: check_development

test:
  <<: *mysql
  database: check_test

staging:
  <<: *postgres
  database: check_production
  username: check
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

production:
  <<: *postgres
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>